"""
FinGraph Deterministic Seed Dataset.
Provides structured entity definitions and transaction records for bootstrapping
local databases and running automated test assertions.
"""
from datetime import datetime, timezone

# ------------------------------------------------------------------------------
# 1. Banks (4 Institutions)
# ------------------------------------------------------------------------------
SEED_BANKS = [
    {"bank_id": "B01", "name": "Apex Global Bank", "country": "US", "routing_number": "021000021"},
    {"bank_id": "B02", "name": "Horizon Trust Bank", "country": "GB", "routing_number": "021000089"},
    {"bank_id": "B03", "name": "Pinnacle Credit Union", "country": "CH", "routing_number": "021000155"},
    {"bank_id": "B04", "name": "Sterling Standard Bank", "country": "SG", "routing_number": "021000244"},
]

# ------------------------------------------------------------------------------
# 2. People & Entities (25 Individuals/Corporates)
# ------------------------------------------------------------------------------
SEED_PEOPLE = [
    {"person_id": "P001", "name": "Alice Vance", "country": "US"},
    {"person_id": "P002", "name": "Bob Martinez", "country": "US"},
    {"person_id": "P003", "name": "Charlie Clark", "country": "US"},
    {"person_id": "P004", "name": "Diana Ross", "country": "US"},
    {"person_id": "P005", "name": "Evan Wright (Mule Broker)", "country": "US"},
    {"person_id": "P006", "name": "Apex Offshore Holdings Ltd", "country": "CH"},
    {"person_id": "P007", "name": "Global Pooling Corp", "country": "GB"},
    {"person_id": "P008", "name": "Hannah Abbott", "country": "GB"},
    {"person_id": "P009", "name": "Ian Malcolm", "country": "GB"},
    {"person_id": "P010", "name": "Venture Syndicate Master", "country": "US"},
    {"person_id": "P011", "name": "Jack Napier", "country": "US"},
    {"person_id": "P012", "name": "Karen Page", "country": "US"},
    {"person_id": "P013", "name": "Liam Neeson", "country": "US"},
    {"person_id": "P014", "name": "Mia Wallace", "country": "US"},
    {"person_id": "P015", "name": "Noah Bennett", "country": "US"},
    {"person_id": "P016", "name": "Olivia Dunham", "country": "US"},
    {"person_id": "P017", "name": "Peter Bishop", "country": "US"},
    {"person_id": "P018", "name": "Apex Corporate Payroll", "country": "US"},
    {"person_id": "P019", "name": "Metro Retail Merchant LLC", "country": "US"},
    {"person_id": "P020", "name": "National Power & Electric", "country": "US"},
    {"person_id": "P021", "name": "Quentin Coldwater", "country": "US"},
    {"person_id": "P022", "name": "Rachel Green", "country": "US"},
    {"person_id": "P023", "name": "Steve Rogers", "country": "US"},
    {"person_id": "P024", "name": "Tony Stark Intermediary", "country": "US"},
    {"person_id": "P025", "name": "Ursula K. Le Guin", "country": "US"},
]

# ------------------------------------------------------------------------------
# 3. Accounts (30 Accounts)
# ------------------------------------------------------------------------------
SEED_ACCOUNTS = [
    # Retail Normal Accounts
    {"account_id": "A001", "account_type": "checking", "owner_id": "P001", "bank_id": "B01", "risk_score": 12.0},
    {"account_id": "A002", "account_type": "checking", "owner_id": "P002", "bank_id": "B01", "risk_score": 15.0},
    {"account_id": "A003", "account_type": "savings", "owner_id": "P003", "bank_id": "B02", "risk_score": 10.0},
    {"account_id": "A004", "account_type": "checking", "owner_id": "P004", "bank_id": "B02", "risk_score": 14.0},
    # Funnel Syndicate (A001..A004 -> A005 -> A006)
    {"account_id": "A005", "account_type": "intermediary", "owner_id": "P005", "bank_id": "B01", "risk_score": 78.0},
    {"account_id": "A006", "account_type": "offshore", "owner_id": "P006", "bank_id": "B03", "risk_score": 85.0},
    # Layered Pool & Exits
    {"account_id": "A007", "account_type": "shell_business", "owner_id": "P007", "bank_id": "B02", "risk_score": 88.0},
    {"account_id": "A008", "account_type": "checking", "owner_id": "P008", "bank_id": "B02", "risk_score": 35.0},
    {"account_id": "A009", "account_type": "checking", "owner_id": "P009", "bank_id": "B02", "risk_score": 35.0},
    # Distribution Syndicate (A010 -> A011..A015)
    {"account_id": "A010", "account_type": "business", "owner_id": "P010", "bank_id": "B01", "risk_score": 75.0},
    {"account_id": "A011", "account_type": "checking", "owner_id": "P011", "bank_id": "B01", "risk_score": 25.0},
    {"account_id": "A012", "account_type": "checking", "owner_id": "P012", "bank_id": "B01", "risk_score": 25.0},
    {"account_id": "A013", "account_type": "checking", "owner_id": "P013", "bank_id": "B04", "risk_score": 25.0},
    {"account_id": "A014", "account_type": "checking", "owner_id": "P014", "bank_id": "B04", "risk_score": 25.0},
    {"account_id": "A015", "account_type": "checking", "owner_id": "P015", "bank_id": "B04", "risk_score": 25.0},
    # Layered Intermediaries
    {"account_id": "A016", "account_type": "intermediary", "owner_id": "P016", "bank_id": "B02", "risk_score": 65.0},
    {"account_id": "A017", "account_type": "intermediary", "owner_id": "P017", "bank_id": "B02", "risk_score": 65.0},
    # Commercial Merchants & Payroll
    {"account_id": "A018", "account_type": "business", "owner_id": "P018", "bank_id": "B01", "risk_score": 5.0},
    {"account_id": "A019", "account_type": "business", "owner_id": "P019", "bank_id": "B01", "risk_score": 8.0},
    {"account_id": "A020", "account_type": "business", "owner_id": "P020", "bank_id": "B01", "risk_score": 4.0},
    # Chain Syndicate (A020 -> A021 -> A022 -> A023 -> A024)
    {"account_id": "A021", "account_type": "intermediary", "owner_id": "P021", "bank_id": "B02", "risk_score": 60.0},
    {"account_id": "A022", "account_type": "intermediary", "owner_id": "P022", "bank_id": "B03", "risk_score": 65.0},
    {"account_id": "A023", "account_type": "intermediary", "owner_id": "P023", "bank_id": "B03", "risk_score": 70.0},
    {"account_id": "A024", "account_type": "offshore", "owner_id": "P024", "bank_id": "B04", "risk_score": 75.0},
    # Circular Flow Syndicate (A025 -> A026 -> A027 -> A025)
    {"account_id": "A025", "account_type": "shell_business", "owner_id": "P025", "bank_id": "B01", "risk_score": 92.0},
    {"account_id": "A026", "account_type": "shell_business", "owner_id": "P001", "bank_id": "B02", "risk_score": 90.0},
    {"account_id": "A027", "account_type": "shell_business", "owner_id": "P002", "bank_id": "B03", "risk_score": 91.0},
    # Layered Sources
    {"account_id": "A028", "account_type": "checking", "owner_id": "P003", "bank_id": "B01", "risk_score": 45.0},
    {"account_id": "A029", "account_type": "checking", "owner_id": "P004", "bank_id": "B02", "risk_score": 45.0},
    {"account_id": "A030", "account_type": "savings", "owner_id": "P005", "bank_id": "B04", "risk_score": 15.0},
]

# ------------------------------------------------------------------------------
# 4. Deterministic Transactions (Normal + 5 Fraud Topologies)
# ------------------------------------------------------------------------------
SEED_TRANSACTIONS = [
    # --- Normal Transactions ---
    {
        "transaction_id": "TX_NORM_001",
        "from_account": "A018",
        "to_account": "A001",
        "amount": 4500.00,
        "currency": "USD",
        "timestamp": "2026-08-01T09:00:00Z",
        "scenario_id": "SC_NORMAL",
        "transaction_type": "salary",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_NORM_002",
        "from_account": "A018",
        "to_account": "A002",
        "amount": 5200.00,
        "currency": "USD",
        "timestamp": "2026-08-01T09:05:00Z",
        "scenario_id": "SC_NORMAL",
        "transaction_type": "salary",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_NORM_003",
        "from_account": "A001",
        "to_account": "A019",
        "amount": 85.50,
        "currency": "USD",
        "timestamp": "2026-08-02T14:30:00Z",
        "scenario_id": "SC_NORMAL",
        "transaction_type": "purchase",
        "channel": "pos",
    },
    {
        "transaction_id": "TX_NORM_004",
        "from_account": "A002",
        "to_account": "A019",
        "amount": 120.00,
        "currency": "USD",
        "timestamp": "2026-08-02T15:00:00Z",
        "scenario_id": "SC_NORMAL",
        "transaction_type": "purchase",
        "channel": "pos",
    },
    {
        "transaction_id": "TX_NORM_005",
        "from_account": "A001",
        "to_account": "A002",
        "amount": 150.00,
        "currency": "USD",
        "timestamp": "2026-08-03T18:00:00Z",
        "scenario_id": "SC_NORMAL",
        "transaction_type": "transfer",
        "channel": "mobile",
    },
    {
        "transaction_id": "TX_NORM_006",
        "from_account": "A002",
        "to_account": "A020",
        "amount": 240.00,
        "currency": "USD",
        "timestamp": "2026-08-04T10:00:00Z",
        "scenario_id": "SC_NORMAL",
        "transaction_type": "bill_payment",
        "channel": "online",
    },

    # --- Pattern A: Funnel / Smurfing (SC_FUNNEL_01) ---
    # A001, A002, A003, A004 -> A005 (Mule) -> A006 (Offshore)
    {
        "transaction_id": "TX_FUN_001",
        "from_account": "A001",
        "to_account": "A005",
        "amount": 8500.00,
        "currency": "USD",
        "timestamp": "2026-08-05T10:00:00Z",
        "scenario_id": "SC_FUNNEL_01",
        "transaction_type": "smurfing",
        "channel": "online",
    },
    {
        "transaction_id": "TX_FUN_002",
        "from_account": "A002",
        "to_account": "A005",
        "amount": 9200.00,
        "currency": "USD",
        "timestamp": "2026-08-05T10:15:00Z",
        "scenario_id": "SC_FUNNEL_01",
        "transaction_type": "smurfing",
        "channel": "online",
    },
    {
        "transaction_id": "TX_FUN_003",
        "from_account": "A003",
        "to_account": "A005",
        "amount": 8900.00,
        "currency": "USD",
        "timestamp": "2026-08-05T10:30:00Z",
        "scenario_id": "SC_FUNNEL_01",
        "transaction_type": "smurfing",
        "channel": "online",
    },
    {
        "transaction_id": "TX_FUN_004",
        "from_account": "A004",
        "to_account": "A005",
        "amount": 9400.00,
        "currency": "USD",
        "timestamp": "2026-08-05T10:45:00Z",
        "scenario_id": "SC_FUNNEL_01",
        "transaction_type": "smurfing",
        "channel": "online",
    },
    {
        "transaction_id": "TX_FUN_005",
        "from_account": "A005",
        "to_account": "A006",
        "amount": 35280.00,
        "currency": "USD",
        "timestamp": "2026-08-05T12:00:00Z",
        "scenario_id": "SC_FUNNEL_01",
        "transaction_type": "pass_through",
        "channel": "wire",
    },

    # --- Pattern B: One-to-Many Distribution (SC_DISTRIB_01) ---
    # A010 -> A011, A012, A013, A014, A015
    {
        "transaction_id": "TX_DIS_001",
        "from_account": "A010",
        "to_account": "A011",
        "amount": 7500.00,
        "currency": "USD",
        "timestamp": "2026-08-06T08:00:00Z",
        "scenario_id": "SC_DISTRIB_01",
        "transaction_type": "dispersion",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_DIS_002",
        "from_account": "A010",
        "to_account": "A012",
        "amount": 7500.00,
        "currency": "USD",
        "timestamp": "2026-08-06T08:05:00Z",
        "scenario_id": "SC_DISTRIB_01",
        "transaction_type": "dispersion",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_DIS_003",
        "from_account": "A010",
        "to_account": "A013",
        "amount": 7500.00,
        "currency": "USD",
        "timestamp": "2026-08-06T08:10:00Z",
        "scenario_id": "SC_DISTRIB_01",
        "transaction_type": "dispersion",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_DIS_004",
        "from_account": "A010",
        "to_account": "A014",
        "amount": 7500.00,
        "currency": "USD",
        "timestamp": "2026-08-06T08:15:00Z",
        "scenario_id": "SC_DISTRIB_01",
        "transaction_type": "dispersion",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_DIS_005",
        "from_account": "A010",
        "to_account": "A015",
        "amount": 7500.00,
        "currency": "USD",
        "timestamp": "2026-08-06T08:20:00Z",
        "scenario_id": "SC_DISTRIB_01",
        "transaction_type": "dispersion",
        "channel": "wire",
    },

    # --- Pattern C: Intermediary Chain (SC_CHAIN_01) ---
    # A020 -> A021 -> A022 -> A023 -> A024
    {
        "transaction_id": "TX_CHN_001",
        "from_account": "A020",
        "to_account": "A021",
        "amount": 35000.00,
        "currency": "USD",
        "timestamp": "2026-08-07T11:00:00Z",
        "scenario_id": "SC_CHAIN_01",
        "transaction_type": "pass_through",
        "channel": "online",
    },
    {
        "transaction_id": "TX_CHN_002",
        "from_account": "A021",
        "to_account": "A022",
        "amount": 34300.00,
        "currency": "USD",
        "timestamp": "2026-08-07T11:30:00Z",
        "scenario_id": "SC_CHAIN_01",
        "transaction_type": "pass_through",
        "channel": "online",
    },
    {
        "transaction_id": "TX_CHN_003",
        "from_account": "A022",
        "to_account": "A023",
        "amount": 33600.00,
        "currency": "USD",
        "timestamp": "2026-08-07T12:00:00Z",
        "scenario_id": "SC_CHAIN_01",
        "transaction_type": "pass_through",
        "channel": "online",
    },
    {
        "transaction_id": "TX_CHN_004",
        "from_account": "A023",
        "to_account": "A024",
        "amount": 32900.00,
        "currency": "USD",
        "timestamp": "2026-08-07T12:30:00Z",
        "scenario_id": "SC_CHAIN_01",
        "transaction_type": "pass_through",
        "channel": "online",
    },

    # --- Pattern D: Circular Flow (SC_CIRCULAR_01) ---
    # A025 -> A026 -> A027 -> A025
    {
        "transaction_id": "TX_CYC_001",
        "from_account": "A025",
        "to_account": "A026",
        "amount": 24000.00,
        "currency": "USD",
        "timestamp": "2026-08-08T14:00:00Z",
        "scenario_id": "SC_CIRCULAR_01",
        "transaction_type": "circular",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_CYC_002",
        "from_account": "A026",
        "to_account": "A027",
        "amount": 23750.00,
        "currency": "USD",
        "timestamp": "2026-08-08T14:15:00Z",
        "scenario_id": "SC_CIRCULAR_01",
        "transaction_type": "circular",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_CYC_003",
        "from_account": "A027",
        "to_account": "A025",
        "amount": 23500.00,
        "currency": "USD",
        "timestamp": "2026-08-08T14:30:00Z",
        "scenario_id": "SC_CIRCULAR_01",
        "transaction_type": "circular",
        "channel": "wire",
    },

    # --- Pattern E: Layered Network (SC_LAYERED_01) ---
    # L1 (A028, A029) -> L2 (A016, A017) -> L3 (A007) -> L4 (A008, A009)
    {
        "transaction_id": "TX_LAY_001",
        "from_account": "A028",
        "to_account": "A016",
        "amount": 9000.00,
        "currency": "USD",
        "timestamp": "2026-08-09T09:00:00Z",
        "scenario_id": "SC_LAYERED_01",
        "transaction_type": "layering",
        "channel": "online",
    },
    {
        "transaction_id": "TX_LAY_002",
        "from_account": "A029",
        "to_account": "A017",
        "amount": 9000.00,
        "currency": "USD",
        "timestamp": "2026-08-09T09:10:00Z",
        "scenario_id": "SC_LAYERED_01",
        "transaction_type": "layering",
        "channel": "online",
    },
    {
        "transaction_id": "TX_LAY_003",
        "from_account": "A016",
        "to_account": "A007",
        "amount": 8800.00,
        "currency": "USD",
        "timestamp": "2026-08-09T10:00:00Z",
        "scenario_id": "SC_LAYERED_01",
        "transaction_type": "layering",
        "channel": "online",
    },
    {
        "transaction_id": "TX_LAY_004",
        "from_account": "A017",
        "to_account": "A007",
        "amount": 8800.00,
        "currency": "USD",
        "timestamp": "2026-08-09T10:15:00Z",
        "scenario_id": "SC_LAYERED_01",
        "transaction_type": "layering",
        "channel": "online",
    },
    {
        "transaction_id": "TX_LAY_005",
        "from_account": "A007",
        "to_account": "A008",
        "amount": 8500.00,
        "currency": "USD",
        "timestamp": "2026-08-09T11:00:00Z",
        "scenario_id": "SC_LAYERED_01",
        "transaction_type": "dispersion",
        "channel": "wire",
    },
    {
        "transaction_id": "TX_LAY_006",
        "from_account": "A007",
        "to_account": "A009",
        "amount": 8500.00,
        "currency": "USD",
        "timestamp": "2026-08-09T11:15:00Z",
        "scenario_id": "SC_LAYERED_01",
        "transaction_type": "dispersion",
        "channel": "wire",
    },
]
